#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
	/config/log/redis \
	/config/media \
	/run/obico

if [ ! -f "/.setup" ]; then
	echo "Initialising obico-server (First time setup)"
	cd /app/obico/backend

	s6-setuidgid abc python3.7 manage.py migrate >/dev/null
	s6-setuidgid abc python3.7 manage.py collectstatic -v 2 --noinput >/dev/null

	touch "/.setup"
fi

# permissions
chown -R abc:abc \
	/config \
	/app \
	/run/obico
