#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/media \
    /run/obico

if [ ! -f "/.setup" ]; then
    echo "Initialising Obico"
    cd /app/obico/backend

    python3.10 manage.py migrate
    python3.10 manage.py collectstatic -v 2 --noinput

    python3.10 manage.py shell <<EOF
from django.contrib.sites.models import Site
if Site.objects.exists():
    site = Site.objects.first()
    site.domain = '${HOST_IP}'
    site.name = 'site'
    site.save()
else:
    Site.objects.create(domain='${HOST_IP}', name='site')
EOF

    touch "/.setup"
fi

# permissions
chown -R abc:abc \
    /config \
    /app \
    /run/obico
