#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# install and start redis for test runs
if [[ -n "${TEST_RUN}" ]]; then
	apt-get update
	apt-get install -y redis-server
	s6-setuidgid abc \
		redis-server --pidfile /run/obico/redis.pid --always-show-logo no --dir /config/ --logfile /config/redis.log &
fi
