#!/usr/bin/with-contenv bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 3333" \
        cd /app/obico/ml_api s6-setuidgid abc \
            gunicorn \
                --bind 0.0.0.0:3333 \
                --workers 1 \
                wsgi
