#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd /app/obico/backend

exec s6-setuidgid abc \
	python3.7 manage.py migrate && python3.7 manage.py collectstatic -v 2 --noinput && python3.7 manage.py runserver --nostatic --noreload 0.0.0.0:3334
