#!/usr/bin/with-contenv bash

check_var() {
    if [ -z "${!1}" ]; then
        echo "Error: No ${2} has been specified in the '${1}' variable. ${3}"
        echo "For more information, see the README: https://github.com/imagegenius/docker-obico#variables"
        sleep infinity
    fi
}

#         Variable    Variable Summary
check_var "REDIS_URL" "Redis URL"
check_var "HOST_IP" "Host IP" "Please set this variable to the domain/ip you access Obico from"

# conflicts of interest (docker-mods are running and we are not set to use them)
if [[ "$DOCKER_MODS" == *"redis"* ]] && [[ "$REDIS_URL" != "redis://localhost:6379" ]]; then
    echo "WARN: It looks like you're running the Redis docker mod, but 'REDIS_URL' is not set to 'redis://localhost:6379'."
fi
